-------------------------------------------------------------------------------
Test set: com.uniantioquia.pruebasunitarias.CalculadoraTest
-------------------------------------------------------------------------------
Tests run: 7, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.411 sec <<< FAILURE!
bucleInfinito(com.uniantioquia.pruebasunitarias.CalculadoraTest)  Time elapsed: 0.319 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 300 milliseconds
	at com.uniantioquia.pruebasunitarias.Calculadora.bufleInfinito(Calculadora.java:72)
	at com.uniantioquia.pruebasunitarias.CalculadoraTest.bucleInfinito(CalculadoraTest.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

